### ISSUE TITLE
Add Splash screen

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE#13]
It would be nice to add a splash screen to replace the default white screen that is shown before the first activity. I'll take this up and do a pull request on the kotlin branch. Before I do that though, what kind of splash screen should we have ?

**Comment by wangerekaharun** [comment]
I have no preference. Any can do so long as you maintain the droidconKE
color schemes.

On Jan 6, 2019 1:38 PM, "Michael Bukachi" <notifications@github.com> wrote:

It would be nice to add a splash screen to replace the default white screen
that is shown before the first activity. I'll take this up and do a pull
request on the kotlin branch. Before I do that though, what kind of splash
screen should we have ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/droidconKE/droidconKE/issues/13>, or mute the thread
